### ISSUE TITLE
Int was called but vector was not initialized for vectorNumber

### ISSUE THREAD

**Issue by vanderkleij** [kevinferrare/spice86#79]
I'm trying to run [Colonization](https://en.wikipedia.org/wiki/Sid_Meier's_Colonization) in spice86. When I start it, it outputs the following and then exits:

```
[Executor] spice86.emulator.ProgramExecutor - Loading file VICEROY.EXE with loader class spice86.emulator.loadablefile.dos.exe.ExeLoader
[Executor] s.e.l.ExecutableFileLoader - Program entry point is 0x12FA:0x71D
[Executor] s.e.i.dos.DosInt21Handler - GET DOS VERSION
[Executor] s.e.i.dos.DosInt21Handler - GET INTERRUPT VECTOR INT 0x67, got 0x0:0x0
[Executor] s.e.i.dos.DosInt21Handler - GET DOS VERSION
[Executor] spice86.ui.Spice86Application - An error occurred during execution
spice86.emulator.errors.UnhandledOperationException: An error occurred while machine was in this state: cycles=204 CS:IP=0x12FA:0x4D16/0x1000:0x7CB6 AX=0x4300 BX=0xFF00 CX=0x0 DX=0x0 SI=0x4FCF DI=0x0 BP=0x0 SP=0x407E SS=0x27D2 DS=0x12FA ES=0x1DD FS=0x0 GS=0x0 flags=0x7202 (  I      ).
Error is: Int was called but vector was not initialized for vectorNumber=0x2F
        at spice86.emulator.cpu.Cpu.interrupt(Cpu.java:1747)
        at spice86.emulator.cpu.Cpu.execOpcode(Cpu.java:927)
        at spice86.emulator.cpu.Cpu.executeNextInstruction(Cpu.java:199)
        at spice86.emulator.machine.Machine.runLoop(Machine.java:307)
        at spice86.emulator.machine.Machine.run(Machine.java:291)
```

Is this something that can be fixed, or is this executable just not supported? Thanks for an awesome tool!

**Comment by kevinferrare** [comment]
Hi, great choice of game!

This means the interrupt handler is not yet implemented in spice86. It can only be solved with code.

For information this repo is not anymore maintained, we converted the program to C# and added code generation, auto import in ghidra and many other things: https://github.com/OpenRakis/Spice86/

**Comment by kevinferrare** [comment]
It will not work in the C# version either because int 0x67 is extended memory and we didnt try  to implement it: https://stanislavs.org/helppc/int_67.html

**Comment by vanderkleij** [comment]
😔

Just tried in C#, and you are correct: it doesn't work. I was hoping it was some minor functionality that I could add myself, but INT 0x67 seems quite complex and not like something a novice to DOS emulators could easily add as a first contribution. Shall I create an issue in the new repository with a request to add it? Or is it something that won't ever be implemented?

**Comment by kevinferrare** [comment]
We plan to implement it eventually since we want to do other games after dune.

You can open an issue of course.

I think a basic implementation of EMS shouldn't be very complex compared to other features, this is just doing copies between real mode address space and "extended memory" (could be hardware ram card, disk, or protected mode accessible memory, but the caller doesn't have to care)

https://en.wikipedia.org/wiki/Expanded_memory

**Comment by kevinferrare** [comment]
We plan to implement it eventually since we want to do other games after dune.

You can open an issue of course.

I think a basic implementation of EMS shouldn't be very complex compared to other features, this is just doing copies between real mode address space and "extended memory" (could be hardware ram card, disk, or protected mode accessible memory, but the caller doesn't have to care)

https://en.wikipedia.org/wiki/Expanded_memory
